name: "Test"

on:
  workflow_dispatch:
  push:
    branches: ["**"]

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Debug CTX: github"
        if: ${{ !github.event.act }}
        continue-on-error: true
        env:
          GITHUB_CTX: ${{ toJSON(github) }}
        run: echo "$GITHUB_CTX"

      - name: "1: Test Local Action"
        id: test
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          multi: |
            one + one
            two + two

      #- name: "2: Test Local Action"
      #  id: test
      #  uses: ./
      #  with:
      #    token: ${{ secrets.GITHUB_TOKEN }}
      #    multi: |
      #      fuck   ,,   , you,   retard
      #
      #- name: "3: Test Local Action"
      #  id: test
      #  uses: ./
      #  with:
      #    token: ${{ secrets.GITHUB_TOKEN }}
      #    multi: |
      #      fuck   ,    you,   retard,
      #
      #- name: "4: Test Local Action"
      #  id: test
      #  uses: ./
      #  with:
      #    token: ${{ secrets.GITHUB_TOKEN }}
      #    multi: |
      #      ,
      #
      #- name: "5: Test Local Action"
      #  id: test
      #  uses: ./
      #  with:
      #    token: ${{ secrets.GITHUB_TOKEN }}
      #    multi: |
      #
      #- name: "Echo Outputs"
      #  run: |
      #    echo results: '${{ steps.test.outputs.results }}'

  #lint:
  #  name: "Lint"
  #  runs-on: ubuntu-latest
  #  timeout-minutes: 5
  #
  #  steps:
  #    - name: "Checkout"
  #      uses: actions/checkout@v4
  #
  #    - name: "Setup Node"
  #      uses: actions/setup-node@v4
  #      with:
  #        node-version: 20
  #
  #    - name: "ESLint"
  #      run: |
  #        npm install
  #        npm run lint

  #build:
  #  name: "Build"
  #  runs-on: ubuntu-latest
  #  timeout-minutes: 5
  #
  #  steps:
  #    - name: "Checkout"
  #      uses: actions/checkout@v4
  #
  #    - name: "Setup Node"
  #      uses: actions/setup-node@v4
  #      with:
  #        node-version: 20
  #
  #    - name: "Build"
  #      run: |
  #        npm install
  #        npm run build
  #
  #    - name: "Verify"
  #      run: |
  #        git status --porcelain dist/
  #        if [ ! -d "dist" ];then
  #          echo "Missing dist directory, run: npm build"
  #          exit 1
  #        fi
  #        if [ -n "$(git status --porcelain dist)" ];then
  #          echo "Build was not run, run: npm build"
  #          exit 1
  #        fi
